FROM node:9.4.0-alpine

RUN apk add --no-cache --update yarn

ENV APP_PATH /usr/src/app
ENV PATH $APP_PATH/node_modules/.bin:$PATH

WORKDIR $APP_PATH

COPY . .

RUN yarn install
RUN yarn build

CMD [ "ln", "-s", "node_modules/react-scripts/bin/react-scripts.js", "node_modules/.bin/react-scripts", ";", \
      "yarn", "start" \
]
